"""create schedule guardian master tables

Revision ID: 3956be0ebb0a
Revises: 4ed06c7c5fe8
Create Date: 2026-05-18 17:06:42.716493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3956be0ebb0a'
down_revision: Union[str, None] = '4ed06c7c5fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_masterDB',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('triage_masterDB',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('guardianDB',
    sa.Column('emrid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('petid', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('triage_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category_masterDB.id'], ),
    sa.ForeignKeyConstraint(['petid'], ['petDB.petid'], ),
    sa.ForeignKeyConstraint(['triage_id'], ['triage_masterDB.id'], ),
    sa.PrimaryKeyConstraint('emrid')
    )
    op.create_table('scheduleDB',
    sa.Column('scheduleid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emrid', sa.Integer(), nullable=False),
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('confirmed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorDB.doctorid'], ),
    sa.ForeignKeyConstraint(['emrid'], ['guardianDB.emrid'], ),
    sa.PrimaryKeyConstraint('scheduleid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduleDB')
    op.drop_table('guardianDB')
    op.drop_table('triage_masterDB')
    op.drop_table('category_masterDB')
    # ### end Alembic commands ###
