"""create petDB

Revision ID: 4ed06c7c5fe8
Revises: 5f2247b0ac15
Create Date: 2026-05-18 15:49:57.497132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed06c7c5fe8'
down_revision: Union[str, None] = '5f2247b0ac15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petDB',
    sa.Column('petid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('petname', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('is_neutered', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['userDB.userid'], ),
    sa.PrimaryKeyConstraint('petid')
    )
    op.drop_column('userDB', 'address')
    op.drop_column('userDB', 'birth_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userDB', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('userDB', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('petDB')
    # ### end Alembic commands ###
