"""update drug

Revision ID: 4f67c206f038
Revises: 672f7924e631
Create Date: 2026-05-21 15:07:47.446570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f67c206f038'
down_revision: Union[str, None] = '672f7924e631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugsDB', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugsDB', 'name')
    # ### end Alembic commands ###
