"""create doctorDB

Revision ID: 5f2247b0ac15
Revises: ac9cb1cd7ab3
Create Date: 2026-05-15 15:18:00.375921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2247b0ac15'
down_revision: Union[str, None] = 'ac9cb1cd7ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctorDB',
    sa.Column('doctorid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loginid', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_initial_password', sa.Boolean(), nullable=False),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=False),
    sa.Column('hospital_address', sa.String(), nullable=True),
    sa.Column('hospital_number', sa.String(), nullable=True),
    sa.Column('business_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('doctorid'),
    sa.UniqueConstraint('business_number'),
    sa.UniqueConstraint('loginid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctorDB')
    # ### end Alembic commands ###
