"""update durgDB

Revision ID: 672f7924e631
Revises: dbce6c783791
Create Date: 2026-05-21 14:58:52.014883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672f7924e631'
down_revision: Union[str, None] = 'dbce6c783791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugsDB', sa.Column('ingredient_en', sa.String(), nullable=False))
    op.alter_column('drugsDB', 'ingredient_kr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drugsDB', 'usage_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('drugsDB', 'dosage')
    op.drop_column('drugsDB', 'duration_days')
    op.drop_column('drugsDB', 'sales_volume')
    op.drop_column('drugsDB', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugsDB', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('drugsDB', sa.Column('sales_volume', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drugsDB', sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drugsDB', sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('drugsDB', 'usage_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drugsDB', 'ingredient_kr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('drugsDB', 'ingredient_en')
    # ### end Alembic commands ###
