"""update drug final

Revision ID: 7c49dfcba726
Revises: 4f67c206f038
Create Date: 2026-05-21 15:36:15.376155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c49dfcba726'
down_revision: Union[str, None] = '4f67c206f038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugsDB', 'usage_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugsDB', sa.Column('usage_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
