"""add checkup_date to petDB

Revision ID: 7de4bee0478d
Revises: e454293dd4bb
Create Date: 2026-05-19 15:15:20.109893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '7de4bee0478d'
down_revision: Union[str, None] = 'e454293dd4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    result = conn.execute(
        text("SELECT column_name FROM information_schema.columns WHERE table_name='petDB' AND column_name='checkup_date'")
    )
    if not result.fetchone():
        op.add_column('petDB', sa.Column('checkup_date', sa.Date(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petDB', 'checkup_date')
    # ### end Alembic commands ###
