"""create chat_historyDB

Revision ID: 9265c9ae7a1f
Revises: 3956be0ebb0a
Create Date: 2026-05-19 13:26:16.046089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9265c9ae7a1f'
down_revision: Union[str, None] = '3956be0ebb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_historyDB',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('petid', sa.Integer(), nullable=False),
    sa.Column('emrid', sa.Integer(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emrid'], ['guardianDB.emrid'], ),
    sa.ForeignKeyConstraint(['petid'], ['petDB.petid'], ),
    sa.ForeignKeyConstraint(['userid'], ['userDB.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vet_scheduleDB')
    op.drop_table('prescriptionDB')
    op.drop_table('drugsDB')
    op.drop_table('doctorEMRDB')
    op.drop_table('doctor_alarmDB')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_alarmDB',
    sa.Column('alarmid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctorid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduleid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contents', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorDB.doctorid'], name=op.f('doctor_alarmDB_doctorid_fkey')),
    sa.ForeignKeyConstraint(['scheduleid'], ['scheduleDB.scheduleid'], name=op.f('doctor_alarmDB_scheduleid_fkey')),
    sa.PrimaryKeyConstraint('alarmid', name=op.f('doctor_alarmDB_pkey'))
    )
    op.create_table('doctorEMRDB',
    sa.Column('doctor_emrid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('petid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctorid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduleid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vet_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorDB.doctorid'], name=op.f('doctorEMRDB_doctorid_fkey')),
    sa.ForeignKeyConstraint(['petid'], ['petDB.petid'], name=op.f('doctorEMRDB_petid_fkey')),
    sa.ForeignKeyConstraint(['scheduleid'], ['scheduleDB.scheduleid'], name=op.f('doctorEMRDB_scheduleid_fkey')),
    sa.PrimaryKeyConstraint('doctor_emrid', name=op.f('doctorEMRDB_pkey'))
    )
    op.create_table('drugsDB',
    sa.Column('drugid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ingredient_kr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usage_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sales_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('drugid', name=op.f('drugsDB_pkey'))
    )
    op.create_table('prescriptionDB',
    sa.Column('prescriptionid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_emrid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drug_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('form', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_emrid'], ['doctorEMRDB.doctor_emrid'], name=op.f('prescriptionDB_doctor_emrid_fkey')),
    sa.ForeignKeyConstraint(['drug_id'], ['drugsDB.drugid'], name=op.f('prescriptionDB_drug_id_fkey')),
    sa.PrimaryKeyConstraint('prescriptionid', name=op.f('prescriptionDB_pkey'))
    )
    op.create_table('vet_scheduleDB',
    sa.Column('vetscheduleid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctorid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorDB.doctorid'], name=op.f('vet_scheduleDB_doctorid_fkey')),
    sa.PrimaryKeyConstraint('vetscheduleid', name=op.f('vet_scheduleDB_pkey'))
    )
    op.drop_table('chat_historyDB')
    # ### end Alembic commands ###
