"""add followupDB

Revision ID: 92d03773b346
Revises: ae4cf8d6c871
Create Date: 2026-05-21 11:23:56.197140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d03773b346'
down_revision: Union[str, None] = 'ae4cf8d6c871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followupDB',
    sa.Column('followupid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emrid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emrid'], ['guardianDB.emrid'], ),
    sa.ForeignKeyConstraint(['userid'], ['userDB.userid'], ),
    sa.PrimaryKeyConstraint('followupid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followupDB')
    # ### end Alembic commands ###
