"""add_ai_summary_and_emergency_alert_to_followup

Revision ID: 9f8fbd8c0bf0
Revises: zz0001_fix
Create Date: 2026-05-23 17:43:58.117957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f8fbd8c0bf0'
down_revision: Union[str, None] = 'zz0001_fix'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_analysisDB',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emrid', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('model_class', sa.String(), nullable=True),
    sa.Column('model_confidence', sa.Numeric(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emrid'], ['guardianDB.emrid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_resultDB',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emrid', sa.Integer(), nullable=False),
    sa.Column('urgency_level', sa.String(), nullable=False),
    sa.Column('urgency_level_num', sa.Integer(), nullable=False),
    sa.Column('vtl_basis', sa.Text(), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=True),
    sa.Column('chief_complaint', sa.String(), nullable=True),
    sa.Column('symptom_onset', sa.String(), nullable=True),
    sa.Column('symptom_keywords', sa.JSON(), nullable=True),
    sa.Column('suspected_diseases', sa.JSON(), nullable=True),
    sa.Column('symptom_summary', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('need_photo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emrid'], ['guardianDB.emrid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitalDB',
    sa.Column('hospitalid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('scheduleid', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=False),
    sa.Column('hospital_address', sa.String(), nullable=False),
    sa.Column('hospital_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorDB.doctorid'], ),
    sa.ForeignKeyConstraint(['scheduleid'], ['scheduleDB.scheduleid'], ),
    sa.PrimaryKeyConstraint('hospitalid')
    )
    op.create_table('validation_resultDB',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emrid', sa.Integer(), nullable=False),
    sa.Column('scheduleid', sa.Integer(), nullable=True),
    sa.Column('overall', sa.String(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('completeness_score', sa.Numeric(), nullable=True),
    sa.Column('accuracy_score', sa.Numeric(), nullable=True),
    sa.Column('consistency_score', sa.Numeric(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emrid'], ['guardianDB.emrid'], ),
    sa.ForeignKeyConstraint(['scheduleid'], ['scheduleDB.scheduleid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_historyDB', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('chat_historyDB', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('chat_historyDB', 'keywords',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('chat_historyDB', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_historyDB', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctorDB', 'business_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('doctorDB', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctorDB', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'doctorDB', ['business_number'])
    op.add_column('doctorEMRDB', sa.Column('vet_note', sa.String(), nullable=True))
    op.alter_column('doctorEMRDB', 'attachments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               nullable=True)
    op.alter_column('doctorEMRDB', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctorEMRDB', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('doctorEMRDB', 'vet_memo')
    op.add_column('doctor_alarmDB', sa.Column('alarmid', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('doctor_alarmDB', 'contents',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('doctor_alarmDB', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('doctor_alarmDB', 'id')
    op.add_column('drugsDB', sa.Column('drugid', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('drugsDB', sa.Column('ingredient_en', sa.String(), nullable=False))
    op.alter_column('drugsDB', 'ingredient_kr',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_column('drugsDB', 'id')
    op.drop_column('drugsDB', 'sales_volume')
    op.drop_column('drugsDB', 'duration_days')
    op.drop_column('drugsDB', 'usage_method')
    op.drop_column('drugsDB', 'dosage')
    op.add_column('followupDB', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('followupDB', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('followupDB', sa.Column('emergency_alert', sa.Boolean(), nullable=True))
    op.alter_column('followupDB', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('guardianDB', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('guardianDB', 'triage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('guardianDB', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('petDB', sa.Column('checkup_date', sa.Date(), nullable=True))
    op.add_column('prescriptionDB', sa.Column('prescriptionid', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('prescriptionDB_drug_id_fkey', 'prescriptionDB', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptionDB', 'drugsDB', ['drug_id'], ['drugid'])
    op.drop_column('prescriptionDB', 'id')
    op.add_column('reportDB', sa.Column('ai_draft_json', sa.JSON(), nullable=True))
    op.alter_column('reportDB', 'scheduleid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('scheduleDB', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('scheduleDB', 'confirmed_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('scheduleDB', 'confirmed_end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('scheduleDB', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduleDB', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('userDB', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('userDB', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('userDB', 'address')
    op.drop_column('userDB', 'birth_date')
    op.add_column('vet_scheduleDB', sa.Column('vetscheduleid', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('vet_scheduleDB', sa.Column('lunch_start_time', sa.Time(), nullable=True))
    op.add_column('vet_scheduleDB', sa.Column('lunch_end_time', sa.Time(), nullable=True))
    op.add_column('vet_scheduleDB', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vet_scheduleDB', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('vet_scheduleDB', 'id')
    op.drop_column('vet_scheduleDB', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vet_scheduleDB', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('vet_scheduleDB', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('vet_scheduleDB', 'updated_at')
    op.drop_column('vet_scheduleDB', 'created_at')
    op.drop_column('vet_scheduleDB', 'lunch_end_time')
    op.drop_column('vet_scheduleDB', 'lunch_start_time')
    op.drop_column('vet_scheduleDB', 'vetscheduleid')
    op.add_column('userDB', sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('userDB', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('userDB', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('userDB', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduleDB', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduleDB', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduleDB', 'confirmed_end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('scheduleDB', 'confirmed_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('scheduleDB', 'deleted_at')
    op.alter_column('reportDB', 'scheduleid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reportDB', 'ai_draft_json')
    op.add_column('prescriptionDB', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'prescriptionDB', type_='foreignkey')
    op.create_foreign_key('prescriptionDB_drug_id_fkey', 'prescriptionDB', 'drugsDB', ['drug_id'], ['id'])
    op.drop_column('prescriptionDB', 'prescriptionid')
    op.drop_column('petDB', 'checkup_date')
    op.alter_column('guardianDB', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('guardianDB', 'triage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('guardianDB', 'deleted_at')
    op.alter_column('followupDB', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('followupDB', 'emergency_alert')
    op.drop_column('followupDB', 'ai_summary')
    op.drop_column('followupDB', 'message')
    op.add_column('drugsDB', sa.Column('dosage', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('drugsDB', sa.Column('usage_method', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('drugsDB', sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drugsDB', sa.Column('sales_volume', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drugsDB', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('drugsDB', 'ingredient_kr',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_column('drugsDB', 'ingredient_en')
    op.drop_column('drugsDB', 'drugid')
    op.add_column('doctor_alarmDB', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('doctor_alarmDB', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctor_alarmDB', 'contents',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('doctor_alarmDB', 'alarmid')
    op.add_column('doctorEMRDB', sa.Column('vet_memo', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('doctorEMRDB', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctorEMRDB', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctorEMRDB', 'attachments',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('doctorEMRDB', 'vet_note')
    op.drop_constraint(None, 'doctorDB', type_='unique')
    op.alter_column('doctorDB', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctorDB', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctorDB', 'business_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('chat_historyDB', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_historyDB', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_historyDB', 'keywords',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('chat_historyDB', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('chat_historyDB', 'is_deleted')
    op.drop_table('validation_resultDB')
    op.drop_table('hospitalDB')
    op.drop_table('triage_resultDB')
    op.drop_table('photo_analysisDB')
    # ### end Alembic commands ###
