"""add lunch time to vet schedule

Revision ID: a2934e146b3b
Revises: 7c49dfcba726
Create Date: 2026-05-21 16:20:18.805278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2934e146b3b'
down_revision: Union[str, None] = '7c49dfcba726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vet_scheduleDB', sa.Column('lunch_start_time', sa.Time(), nullable=True))
    op.add_column('vet_scheduleDB', sa.Column('lunch_end_time', sa.Time(), nullable=True))
    op.add_column('vet_scheduleDB', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vet_scheduleDB', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('vet_scheduleDB', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vet_scheduleDB', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('vet_scheduleDB', 'updated_at')
    op.drop_column('vet_scheduleDB', 'created_at')
    op.drop_column('vet_scheduleDB', 'lunch_end_time')
    op.drop_column('vet_scheduleDB', 'lunch_start_time')
    # ### end Alembic commands ###
