"""add new tables

Revision ID: d17ddfd496dc
Revises: e6bbfa319c9a
Create Date: 2026-05-18 17:40:14.873192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17ddfd496dc'
down_revision: Union[str, None] = 'e6bbfa319c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugsDB',
    sa.Column('drugid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ingredient_kr', sa.String(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('usage_method', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('sales_volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('drugid')
    )
    op.create_table('vet_scheduleDB',
    sa.Column('vetscheduleid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorDB.doctorid'], ),
    sa.PrimaryKeyConstraint('vetscheduleid')
    )
    op.create_table('doctorEMRDB',
    sa.Column('doctor_emrid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('petid', sa.Integer(), nullable=False),
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('scheduleid', sa.Integer(), nullable=False),
    sa.Column('vet_note', sa.String(), nullable=True),
    sa.Column('attachments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorDB.doctorid'], ),
    sa.ForeignKeyConstraint(['petid'], ['petDB.petid'], ),
    sa.ForeignKeyConstraint(['scheduleid'], ['scheduleDB.scheduleid'], ),
    sa.PrimaryKeyConstraint('doctor_emrid')
    )
    op.create_table('doctor_alarmDB',
    sa.Column('alarmid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('scheduleid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('contents', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorDB.doctorid'], ),
    sa.ForeignKeyConstraint(['scheduleid'], ['scheduleDB.scheduleid'], ),
    sa.PrimaryKeyConstraint('alarmid')
    )
    op.create_table('prescriptionDB',
    sa.Column('prescriptionid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_emrid', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_emrid'], ['doctorEMRDB.doctor_emrid'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugsDB.drugid'], ),
    sa.PrimaryKeyConstraint('prescriptionid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescriptionDB')
    op.drop_table('doctor_alarmDB')
    op.drop_table('doctorEMRDB')
    op.drop_table('vet_scheduleDB')
    op.drop_table('drugsDB')
    # ### end Alembic commands ###
