"""add user address

Revision ID: dbaea7d3d6f4
Revises: d17ddfd496dc
Create Date: 2026-05-20 03:00:54.531246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbaea7d3d6f4'
down_revision: Union[str, None] = 'd17ddfd496dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_historyDB')
    op.drop_column('petDB', 'checkup_date')
    op.add_column('userDB', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userDB', 'address')
    op.add_column('petDB', sa.Column('checkup_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_table('chat_historyDB',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('petid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emrid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['emrid'], ['guardianDB.emrid'], name='chat_historyDB_emrid_fkey'),
    sa.ForeignKeyConstraint(['petid'], ['petDB.petid'], name='chat_historyDB_petid_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['userDB.userid'], name='chat_historyDB_userid_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_historyDB_pkey')
    )
    # ### end Alembic commands ###
