"""create hospitaldb

Revision ID: dbce6c783791
Revises: 92d03773b346
Create Date: 2026-05-21 14:07:12.816721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbce6c783791'
down_revision: Union[str, None] = '92d03773b346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitalDB',
    sa.Column('hospitalid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('scheduleid', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=False),
    sa.Column('hospital_address', sa.String(), nullable=False),
    sa.Column('hospital_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorDB.doctorid'], ),
    sa.ForeignKeyConstraint(['scheduleid'], ['scheduleDB.scheduleid'], ),
    sa.PrimaryKeyConstraint('hospitalid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospitalDB')
    # ### end Alembic commands ###
