"""create doctor_alarmDB  drugsDB doctorEMRDB prescriptionDB vet_scheduleDB tables

Revision ID: e6bbfa319c9a
Revises: 3956be0ebb0a
Create Date: 2026-05-18 17:36:31.784942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bbfa319c9a'
down_revision: Union[str, None] = '3956be0ebb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
